<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "formation_fsc"
 *
 * Generated by ali.werghemmi@softtodo.com 2022-04-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/



$EM_CONF[$_EXTKEY] = [
    'title' => 'SOFTTODO extension for fluid styled content usage',
    'description' => 'This TYPO3 extension is an example to use Fluid Styled Content for creating contents',
    'category' => 'plugin',
    'author' => 'SOFTTODO Documentation Team',
    'author_company' => 'SOFTTODO',
    'author_email' => 'ali.werghemmi@softtodo.com',
    'state' => 'stable',
    'clearCacheOnLoad' => true,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '',
            'impexp' => '',
        ]
    ],
    'autoload' => [
        'psr-4' => [
            'SOFTTODO\\FormationFsc\\' => 'Classes'
        ]
    ],
];
